# This is a basic workflow to help you get started with Actions

name: Build and Deploy

on:
  push:
    branches:
      - new-version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: install cuttlebelle
        run: sudo npm  install -g cuttlebelle
      - name: install dependencies
        run: npm install
      - name: Run a one-line script
        run: npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: site # The folder the action should deploy.
